server:
  port: 4320
spring:
  application:
    name: worldcup-management-server
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/worldcup_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: worldcup_management
    password: 25fZ2PkDfjiFekPa
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
app:
  archive-path: ../skill/archive
  admin:
    username: admin
    password: admin123456
springdoc:
  swagger-ui:
    path: /swagger-ui.html
