const labelMaps = {
  matchStatus: {
    SCHEDULED: '未开赛',
    PRE_MATCH: '赛前',
    LIVE: '进行中',
    IN_PROGRESS: '进行中',
    FINISHED: '已完赛',
    FINAL: '已完赛',
    POSTPONED: '延期',
    CANCELLED: '取消',
    UNKNOWN: '待确认',
  },
  integrityStatus: {
    PASS: '通过',
    COMPLETE: '资料齐',
    PARTIAL: '部分可读',
    STALE: '需更新',
    PENDING: '待确认',
    MISSING: '缺失',
    CONFLICT: '有冲突',
    BLOCKED: '阻塞',
    UNKNOWN: '待确认',
  },
  severity: {
    CRITICAL: '极高',
    HIGH: '高',
    MEDIUM: '中',
    LOW: '低',
    INFO: '信息',
    UNKNOWN: '待评估',
  },
  riskLevel: {
    CRITICAL: '极高风险',
    HIGH: '高风险',
    MEDIUM: '中风险',
    LOW: '低风险',
    UNKNOWN: '待评估',
  },
  oddsSnapshot: {
    LIVE: '实时市场',
    PRE_MATCH: '赛前快照',
    POST_MATCH_ARCHIVED: '赛后归档',
  },
  oddsSelectionStatus: {
    OPEN: '市场开放',
    ACTIVE: '可用',
    AVAILABLE: '可用',
    AVAILABLE_OR_ARCHIVED: '可用/归档',
    SUSPENDED: '暂停',
    CLOSED: '已关闭',
    SETTLED: '已结算',
  },
  marketCode: {
    H2H_1X2: '胜平负',
    SPREAD: '让球/让分',
    TOTAL_GOALS: '总进球',
    HAD: '胜平负',
    HHAD: '让球胜平负',
  },
  impactDirection: {
    POSITIVE: '利好',
    NEGATIVE: '利空',
    NEUTRAL: '中性',
    MIXED: '多空混合',
    UNKNOWN: '影响待评估',
  },
  evidenceLevel: {
    OFFICIAL: '官方来源',
    VERIFIED: '已验证',
    HIGH: '高可信',
    MEDIUM: '中可信',
    LOW: '低可信',
    DERIVED: '派生资料',
    STRUCTURED_API: '结构化接口',
    WEB_PAGE: '网页来源',
    UNKNOWN: '待确认',
  },
  evidenceQualityLevel: {
    HIGH: '高可信',
    MEDIUM: '中可信',
    LOW: '低可信',
    UNRATED: '未评分',
    UNKNOWN: '待评估',
  },
  evidenceFreshnessStatus: {
    FRESH: '新鲜',
    AGING: '需复核',
    STALE: '已过期',
    FUTURE: '未来时间',
    UNKNOWN: '时间待同步',
  },
  factorCategory: {
    WEATHER: '天气',
    VENUE: '场地',
    ATTENDANCE: '上座/观众',
    BROADCAST: '转播信息',
    REFEREE: '裁判',
    DISCIPLINE: '纪律/牌面',
    CARD: '红黄牌',
    INFRACTION_PROFILE: '犯规/越位样本',
    INJURY: '伤停',
    TRAINING: '训练',
    WORKLOAD: '出场负荷',
    PLAYING_TIME: '出场时间',
    FITNESS: '体能/恢复',
    FORM: '近期赛果状态',
    TOURNAMENT_FORM: '本届赛果走势',
    RECENT_RESULTS: '近期赛果',
    RESULT_TREND: '赛果走势',
    KEY_PLAYER: '关键球员',
    PLAYER_IMPACT: '球员影响',
    ATTACK_CONTRIBUTION: '进攻贡献',
    SCORING: '进球模式',
    SET_PIECE: '定位球/特殊进球',
    GOAL_TIMING: '进球时间段',
    ATTACK_PATTERN: '进攻方式',
    TECHNICAL_STYLE: '基础技术风格',
    GOALKEEPING: '门将/防守承压',
    SHOT_STOPPING: '扑救/守门',
    DEFENSIVE_PRESSURE: '防守承压',
    SQUAD_PROFILE: '阵容结构/年龄经验',
    ROSTER_PROFILE: '阵容名单画像',
    AGE_EXPERIENCE: '年龄经验画像',
    TEAM_EXPERIENCE: '国家队经验画像',
    CLUB_DISTRIBUTION: '俱乐部分布',
    HEIGHT_PROFILE: '身高画像',
    POSITION_PROFILE: '位置分布画像',
    LINEUP_STRUCTURE: '首发位置结构',
    STARTING_XI_PROFILE: '已确认首发画像',
    FORMATION_PROFILE: '阵型/位置结构',
    TECHNICAL: '基础技术统计',
    PASSING: '传球画像',
    DEFENSIVE_ACTION: '防守动作',
    SCHEDULE: '赛程',
    TRAVEL: '旅途',
    REST: '休息',
    GROUP_QUALIFICATION: '出线形势',
    QUALIFICATION: '出线资格',
    KNOCKOUT: '淘汰赛阶段',
    ADVANCEMENT: '晋级路径',
    MOTIVATION: '战意',
    ROTATION: '轮换',
    PRESS_CONFERENCE: '发布会',
    TEAM_NEWS: '球队新闻',
    NEWS: '新闻',
    LOCKER_ROOM: '更衣室',
    PUBLIC_OPINION: '舆论',
    PUBLIC_SENTIMENT: '公众舆情',
    FAN_SENTIMENT: '球迷情绪',
    MARKET: '赔率/市场价格',
    MARKET_SIGNAL: '市场价格信号',
    PUBLIC_BETTING: '公众热度',
    ODDS: '赔率/市场',
    HISTORY: '历史交锋',
    TACTICAL_MATCHUP: '战术对位',
    TACTIC: '战术对位',
    TRAVEL_REST: '旅行/休息',
    OTHER: '其他',
  },
  factorType: {
    BROADCAST: '转播/赛程信息',
    STADIUM: '球场',
    REFEREE: '裁判',
    OFFICIAL: '比赛官员/主裁',
    REFEREE_ASSIGNMENT: '裁判指派',
    REFEREE_SOURCE_AUDIT: '裁判来源追溯',
    MATCH_OFFICIALS: '裁判组',
    ASSISTANT_REFEREE: '助理裁判',
    FOURTH_OFFICIAL: '第四官员',
    VAR: '视频助理裁判',
    VIDEO_ASSISTANT_REFEREE: '视频助理裁判',
    ATTENDANCE: '上座/观众',
    CROWD: '现场上座',
    TV_CHANNELS: '转播平台',
    WEATHER: '天气',
    WARM: '偏暖天气',
    MILD: '温和天气',
    COMFORTABLE: '舒适天气',
    HEAT: '高温',
    HEAT_HUMIDITY: '高温高湿',
    HEAT_THUNDERSTORM: '高温雷暴',
    THUNDERSTORM_HEAT: '雷暴高温',
    HUMID_THUNDERSTORM: '潮湿雷暴',
    RAIN_THUNDERSTORM: '降雨雷暴',
    DANGEROUS_HEAT: '危险热感',
    EXTREME_HEAT_ALERT: '极端高温警报',
    TEMPERATURE_PITCH: '天气/草皮',
    CARD_TENDENCY: '判罚倾向',
    TEAM_CARD_ACCUMULATION: '球队累计牌面',
    PLAYER_CARD_ACCUMULATION: '球员累计牌面',
    NEXT_MATCH_DISCIPLINE_WATCH: '下场纪律关注',
    YELLOW_CARD_ACCUMULATION: '累计黄牌',
    RED_CARD_ACCUMULATION: '累计红牌',
    SECOND_YELLOW_CARD: '第二黄牌',
    PLAYER_TOURNAMENT_MINUTES: '球员本届累计分钟',
    PLAYER_RECENT_3_MINUTES: '球员近三场分钟',
    TEAM_HIGH_WORKLOAD_PLAYER_COUNT: '高负荷球员数',
    TEAM_CONSECUTIVE_STARTERS: '连续首发人数',
    STARTING_CONTINUITY: '首发连续性',
    ROTATION_PRESSURE: '轮换压力',
    MINUTES_DERIVED: '派生出场分钟',
    NEXT_MATCH_WORKLOAD_WATCH: '下场负荷关注',
    RECENT_RESULTS: '近期赛果',
    TEAM_RECENT_RESULTS: '球队近期赛果',
    TEAM_TOURNAMENT_FORM: '球队本届赛果走势',
    RESULT_STREAK: '连续赛果',
    TOURNAMENT_FORM: '本届赛果走势',
    FORM_TREND: '状态走势',
    RESULT_TREND: '赛果走势',
    UNBEATEN_STREAK: '连续不败',
    WINLESS_STREAK: '连续未胜',
    CLEAN_SHEET_TREND: '零封走势',
    GOAL_TIME_BUCKET: '进球时间段',
    FIRST_GOAL_MINUTE: '首球时间',
    LATE_GOAL: '末段进球',
    SPECIAL_SCORING_PROFILE: '特殊进球方式',
    HEADER_GOAL: '头球进球',
    FREE_KICK_GOAL: '任意球进球',
    PENALTY_SCORED: '点球命中',
    PENALTY_MISSED: '点球罚失',
    OWN_GOAL: '乌龙球',
    CORNER_GOAL: '角球进球',
    SET_PIECE_GOAL: '定位球进球',
    CROSS_GOAL: '传中进球',
    THROUGH_BALL_GOAL: '直塞进球',
    FAST_BREAK_GOAL: '快速反击进球',
    PLAYER_GOAL_INVOLVEMENT: '球员进球参与',
    KEY_PLAYER_CONTRIBUTION: '关键球员进球参与',
    GOAL_CONTRIBUTION: '进球参与贡献',
    TOP_SCORER_CONTRIBUTION: '主要得分贡献',
    ASSIST_CONTRIBUTION: '助攻贡献',
    CONTRIBUTION_DISTRIBUTION: '贡献分布',
    TECHNICAL_BOXSCORE: '基础技术统计',
    SHOT_PROFILE: '射门画像',
    TEAM_SHOT_PROFILE: '球队射门画像',
    POSSESSION_PROFILE: '控球画像',
    PASSING_PROFILE: '传球画像',
    POSSESSION_PASSING_PROFILE: '控球传球画像',
    CROSSING_PROFILE: '传中画像',
    CORNER_PROFILE: '角球画像',
    FOUL_PROFILE: '犯规画像',
    DEFENSIVE_ACTION_PROFILE: '防守动作画像',
    DEFENSIVE_ACTIVITY_PROFILE: '防守活动画像',
    FOUL_OFFSIDE_PENALTY_PROFILE: '犯规/越位/点球尝试画像',
    SAVE_PRESSURE_PROFILE: '扑救与承压画像',
    SAVE_PROFILE: '门将扑救画像',
    GOALKEEPING_SAVE_PROFILE: '门将扑救画像',
    GOALKEEPER_SAVE_PROFILE: '门将扑救画像',
    SHOT_STOPPING_PROFILE: '扑救画像',
    DEFENSIVE_PRESSURE_PROFILE: '防守承压画像',
    TEAM_SIDE_ROSTER_BASELINE: '球队名单结构画像',
    SQUAD_PROFILE: '阵容结构画像',
    ROSTER_PROFILE: '阵容名单画像',
    AGE_EXPERIENCE_STRUCTURE: '年龄经验结构画像',
    AGE_PROFILE: '年龄画像',
    TEAM_EXPERIENCE_PROFILE: '国家队经验画像',
    CLUB_DISTRIBUTION_PROFILE: '俱乐部分布画像',
    HEIGHT_PROFILE: '身高画像',
    POSITION_PROFILE: '位置分布画像',
    CONFIRMED_STARTING_XI_STRUCTURE: '已确认首发位置结构',
    CONFIRMED_STARTING_POSITION_PROFILE: '已确认首发位置画像',
    LINEUP_STRUCTURE_PROFILE: '首发位置结构画像',
    STARTING_XI_PROFILE: '已确认首发画像',
    FORMATION_PROFILE: '阵型/位置结构画像',
    INJURY: '伤停',
    PLAYER_INJURY: '球员伤停',
    TRAINING: '训练',
    NEWS: '新闻',
    TRAVEL_REST: '旅行/休息',
    REST_DAYS: '休息天数',
    MATCHDAY: '赛程时间',
    TRAVEL_DISTANCE: '旅行距离',
    VENUE_TRANSITION: '场馆转换',
    SCHEDULE_DENSITY: '赛程密度',
    MOTIVATION: '战意',
    GROUP_QUALIFICATION: '出线形势',
    QUALIFICATION: '出线状态',
    QUALIFICATION_STATUS: '出线状态',
    ADVANCEMENT: '晋级路径',
    ADVANCEMENT_STATUS: '晋级状态',
    ROUND_OF_32_STAGE: '32强赛阶段',
    ROUND_OF_32_PATH: '32强晋级路径',
    QUALIFIED_TOP2: '小组前二出线',
    QUALIFIED_BEST_THIRD: '成绩较好小组第三出线',
    GROUP_STAGE_ELIMINATED: '小组赛出局',
    ADVANCED_TO_ROUND_OF_16: '晋级16强',
    ELIMINATED_IN_ROUND_OF_32: '32强赛出局',
    KNOCKOUT_STAGE: '淘汰赛阶段',
    KNOCKOUT_ELIMINATION_CONTEXT: '淘汰赛晋级/出局规则',
    TOURNAMENT_FORMAT: '赛事赛制',
    ROUND_OF_32: '32强赛',
    ROTATION: '轮换',
    LOCKER_ROOM: '更衣室',
    PRESS_CONFERENCE: '主帅发布会',
    OFFICIAL_TEAM_NEWS: '官方球队新闻',
    PUBLIC_BETTING: '公众热度',
    MARKET_SIGNAL: '市场价格信号',
    MARKET_PRICE_SNAPSHOT: '市场价格快照',
    MARKET_PRICE: '市场价格',
    IMPLIED_PROBABILITY: '隐含概率',
    PRE_MATCH: '赛前快照',
    POST_MATCH_ARCHIVED: '赛后归档快照',
    H2H_1X2: '胜平负',
    SPREAD: '让球/让分',
    TOTAL_GOALS: '总进球',
    MATCH_WIN: '胜平负市场',
    HEAD_TO_HEAD: '历史交锋',
    TACTICAL_MATCHUP: '战术对位',
    TACTIC: '战术对位',
    OTHER: '其他',
  },
  riskType: {
    PACE: '比赛节奏',
    RAIN: '降雨',
    PUBLIC_OVERHEAT: '热度过高',
    INJURY: '伤停',
    WEATHER: '天气',
    LINEUP: '阵容',
    ODDS: '赔率',
    MARKET: '赔率/市场价格',
    MARKET_PRICE_SNAPSHOT: '市场价格快照',
    PUBLIC_BETTING: '公众热度',
    TRAVEL: '旅途',
    REST: '休息',
    REFEREE: '裁判',
    DISCIPLINE: '纪律风险',
    CARD_ACCUMULATION: '累计牌面',
    SUSPENSION_WATCH: '停赛关注',
    INFRACTION_PROFILE: '犯规/越位样本',
    FOUL_OFFSIDE_PENALTY_PROFILE: '犯规/越位/点球尝试画像',
    MOTIVATION: '战意',
    GROUP_QUALIFICATION: '出线形势',
    QUALIFICATION: '出线状态',
    QUALIFICATION_STATUS: '出线状态',
    ADVANCEMENT_STATUS: '晋级状态',
    KNOCKOUT: '淘汰赛阶段',
    ROUND_OF_32_STAGE: '32强赛阶段',
    ROUND_OF_32_PATH: '32强晋级路径',
    ADVANCED_TO_ROUND_OF_16: '晋级16强',
    ELIMINATED_IN_ROUND_OF_32: '32强赛出局',
    KNOCKOUT_ELIMINATION_CONTEXT: '淘汰赛晋级/出局规则',
    ROTATION: '轮换',
    TACTIC: '战术',
    SCORING: '进球模式',
    SET_PIECE: '定位球/特殊进球',
    GOAL_TIMING: '进球时间段',
    ATTACK_PATTERN: '进攻方式',
    KEY_PLAYER: '关键球员',
    PLAYER_IMPACT: '球员影响',
    ATTACK_CONTRIBUTION: '进攻贡献',
    KEY_PLAYER_CONTRIBUTION: '关键球员进球参与',
    HEADER_GOAL: '头球进球',
    FREE_KICK_GOAL: '任意球进球',
    OWN_GOAL: '乌龙球',
    TECHNICAL_STYLE: '基础技术风格',
    GOALKEEPING: '门将/防守承压',
    SAVE_PRESSURE_PROFILE: '扑救与承压画像',
    SAVE_PROFILE: '门将扑救画像',
    GOALKEEPING_SAVE_PROFILE: '门将扑救画像',
    GOALKEEPER_SAVE_PROFILE: '门将扑救画像',
    SHOT_STOPPING_PROFILE: '扑救画像',
    DEFENSIVE_PRESSURE_PROFILE: '防守承压画像',
    SQUAD_PROFILE: '阵容结构/年龄经验',
    TEAM_SIDE_ROSTER_BASELINE: '球队名单结构画像',
    AGE_EXPERIENCE_STRUCTURE: '年龄经验结构画像',
    ROSTER_PROFILE: '阵容名单画像',
    CLUB_DISTRIBUTION_PROFILE: '俱乐部分布画像',
    LINEUP_STRUCTURE: '首发位置结构',
    CONFIRMED_STARTING_XI_STRUCTURE: '已确认首发位置结构',
    CONFIRMED_STARTING_POSITION_PROFILE: '已确认首发位置画像',
    LINEUP_STRUCTURE_PROFILE: '首发位置结构画像',
    STARTING_XI_PROFILE: '已确认首发画像',
    FORMATION_PROFILE: '阵型/位置结构画像',
    TECHNICAL_BOXSCORE: '基础技术统计',
    SHOT_PROFILE: '射门画像',
    PASSING_PROFILE: '传球画像',
    DEFENSIVE_ACTION_PROFILE: '防守动作画像',
    PUBLIC_OPINION: '舆论',
    UNKNOWN: '待评估',
  },
  sourceType: {
    OFFICIAL: '官方来源',
    REFEREE_ASSIGNMENT: '裁判指派来源',
    MATCH_OFFICIALS: '裁判组来源',
    VENUE_CONTEXT: '场馆信息来源',
    BROADCAST: '转播信息来源',
    ATTENDANCE: '上座信息来源',
    GROUP_QUALIFICATION: '出线形势来源',
    KNOCKOUT_CONTEXT: '淘汰赛阶段来源',
    QUALIFICATION_DERIVED: '出线状态派生来源',
    KNOCKOUT_BRACKET: '淘汰赛路径来源',
    ADVANCEMENT_RESULT: '晋级结果来源',
    FORM_DERIVED: '近期赛果派生来源',
    RECENT_RESULTS_DERIVED: '近期赛果派生来源',
    TOURNAMENT_FORM_DERIVED: '本届赛果派生来源',
    KEY_PLAYER_CONTRIBUTION_DERIVED: '关键球员贡献派生来源',
    GOAL_CONTRIBUTION_DERIVED: '进球参与派生来源',
    MARKET_PRICE_SNAPSHOT_DERIVED: '市场价格快照派生来源',
    FOUL_OFFSIDE_PENALTY_PROFILE_DERIVED: '犯规/越位样本派生来源',
    GOALKEEPING_SAVE_PROFILE_DERIVED: '门将扑救画像派生来源',
    SAVE_PRESSURE_PROFILE_DERIVED: '扑救与承压画像派生来源',
    SQUAD_LIST: '官方名单来源',
    SQUAD_PROFILE_DERIVED: '阵容结构画像派生来源',
    TEAM_SQUAD_PROFILE_DERIVED: '球队名单画像派生来源',
    LINEUP_STRUCTURE_DERIVED: '首发位置结构派生来源',
    CONFIRMED_LINEUP_DERIVED: '已确认阵容派生来源',
    TOURNAMENT_FORM: '本届赛果走势来源',
    TOURNAMENT_FORMAT: '赛事赛制来源',
    SCHEDULE_RESULT: '赛程赛果',
    WEB_MATCH_PAGE: '比赛网页',
    STRUCTURED_SUMMARY: '结构化摘要',
    STRUCTURED_API: '结构化接口',
    SCOREBOARD_STATUS: '比分牌状态',
    NEWS: '新闻来源',
    ODDS: '赔率来源',
    SENTIMENT: '舆情来源',
  },
  eventType: {
    KICKOFF: '开球',
    START_DELAY: '开赛延迟',
    END_DELAY: '结束延迟',
    START_2ND_HALF: '下半场开始',
    HALFTIME: '半场结束',
    END_REGULAR_TIME: '常规时间结束',
    GOAL: '进球',
    GOAL_HEADER: '头球进球',
    GOAL_VOLLEY: '凌空进球',
    GOAL_FREE_KICK: '任意球进球',
    OWN_GOAL: '乌龙球',
    PENALTY_GOAL: '点球进球',
    PENALTY_SCORED: '点球命中',
    PENALTY_MISSED: '点球罚失',
    YELLOW_CARD: '黄牌',
    RED_CARD: '红牌',
    SECOND_YELLOW_CARD: '第二黄牌',
    VAR_RED_CARD_UPGRADE: 'VAR 升级红牌',
    SUBSTITUTION: '换人',
    HALF_TIME: '半场',
    FULL_TIME: '全场结束',
  },
  statsType: {
    ESPN_FULL_TIME: 'ESPN 全场统计',
    RECENT: '近期表现',
    FULL_TIME: '全场统计',
  },
  conflictType: {
    KICKOFF: '开球时间',
    SCORE: '比分',
    LINEUP: '阵容',
    ODDS: '赔率',
    STATUS: '比赛状态',
    SOURCE: '来源差异',
    MATCH_HOME_AWAY_ORDER_CONFLICT: '主客队顺序冲突',
    MATCH_RESULT_STATUS_CONFLICT: '赛果状态冲突',
    MATCH_STATUS_CONFLICT: '比赛状态冲突',
  },
  fieldName: {
    'home_team_key/away_team_key': '主客队标识',
    result_status: '赛果状态',
    status: '比赛状态',
    kickoffTime: '开球时间',
    kickoff_time: '开球时间',
  },
  resolutionStatus: {
    PENDING: '待处理',
    RESOLVED: '已处理',
    REJECTED: '已驳回',
    AUTO_RESOLVED: '自动处理',
    UNKNOWN: '待确认',
  },
  position: {
    SUB: '替补席',
    GK: '门将',
    DF: '后卫',
    MF: '中场',
    FW: '前锋',
    G: '门将',
    D: '后卫',
    M: '中场',
    F: '前锋',
    CD: '中后卫',
    'CD-R': '右中卫',
    'CD-L': '左中卫',
    RB: '右后卫',
    LB: '左后卫',
    SW: '清道夫',
    DM: '防守型中场',
    CM: '中前卫',
    'CM-R': '右中前卫',
    'CM-L': '左中前卫',
    LM: '左中场',
    RM: '右中场',
    AM: '前腰',
    'AM-R': '右前腰',
    'AM-L': '左前腰',
    CF: '中锋',
    'CF-R': '右中锋',
    'CF-L': '左中锋',
    RCF: '右中锋',
    RF: '右边锋',
    LF: '左边锋',
  },
  playerStatus: {
    SQUAD_LISTED: '名单内',
    FIT: '可出场',
    INJURED: '伤停',
    SUSPENDED: '停赛',
    DOUBTFUL: '出战存疑',
    UNKNOWN: '待同步',
  },
  profileReadinessLevel: {
    GOOD: '准备充分',
    PARTIAL: '基础可读',
    WEAK: '偏薄弱',
    UNKNOWN: '待评估',
  },
  lineupRole: {
    STARTER: '首发',
    SUBSTITUTE: '替补',
    BENCH: '替补',
    CAPTAIN: '队长',
    CORE: '核心',
  },
  factType: {
    STYLE: '风格',
    FORM: '状态',
    INJURY: '伤病',
    TACTIC: '战术',
    PROFILE: '画像',
    DISCIPLINE: '纪律/牌面',
    CARD: '红黄牌',
    WORKLOAD: '出场负荷',
    PLAYING_TIME: '出场时间',
    SCORING: '进球模式',
    SET_PIECE: '定位球/特殊进球',
    GOAL_TIMING: '进球时间段',
    ATTACK_PATTERN: '进攻方式',
    KEY_PLAYER_CONTRIBUTION: '关键球员进球参与',
    GOAL_CONTRIBUTION: '进球参与贡献',
    TECHNICAL_STYLE: '基础技术风格',
    FOUL_OFFSIDE_PENALTY_PROFILE: '犯规/越位/点球尝试画像',
    GOALKEEPING_SAVE_PROFILE: '门将扑救画像',
    GOALKEEPER_SAVE_PROFILE: '门将扑救画像',
    SAVE_PRESSURE_PROFILE: '扑救与承压画像',
    DEFENSIVE_PRESSURE_PROFILE: '防守承压画像',
    SQUAD_PROFILE: '阵容结构与年龄经验',
    TEAM_SIDE_ROSTER_BASELINE: '球队名单结构画像',
    AGE_EXPERIENCE_STRUCTURE: '年龄经验结构画像',
    ROSTER_PROFILE: '阵容名单画像',
    CLUB_DISTRIBUTION_PROFILE: '俱乐部分布画像',
    LINEUP_STRUCTURE_PROFILE: '首发位置结构画像',
    CONFIRMED_STARTING_XI_STRUCTURE: '已确认首发位置结构',
    CONFIRMED_STARTING_POSITION_PROFILE: '已确认首发位置画像',
    STARTING_XI_PROFILE: '已确认首发画像',
    FORMATION_PROFILE: '阵型/位置结构画像',
    TOURNAMENT_TECHNICAL_SUMMARY: '世界杯基础技术统计',
    SHOT_PROFILE: '射门画像',
    PASSING_PROFILE: '传球画像',
    DEFENSIVE_ACTION: '防守动作',
    ROTATION: '轮换',
    GROUP_QUALIFICATION: '出线形势',
    QUALIFICATION: '出线状态',
    QUALIFICATION_STATUS: '出线状态',
    KNOCKOUT: '淘汰赛阶段',
    ADVANCEMENT: '晋级路径',
    ADVANCEMENT_STATUS: '晋级状态',
    FITNESS: '体能/恢复',
    TOURNAMENT_FORM: '本届赛果走势',
    RECENT_RESULTS: '近期赛果',
    RESULT_TREND: '赛果走势',
    HISTORY: '历史',
    NEWS: '新闻',
    OTHER: '其他',
  },
  conclusionType: {
    LEAN_HOME: '倾向主队',
    LEAN_AWAY: '倾向客队',
    LEAN_DRAW: '倾向平局',
    WATCH_ONLY: '仅观察',
    NO_BET: '不建议介入',
    UNKNOWN: '结论待定',
  },
  lessonType: {
    MARKET: '市场经验',
    RISK: '风险经验',
    TEAM: '球队经验',
    PLAYER: '球员经验',
    TACTIC: '战术经验',
    DATA: '数据经验',
    OTHER: '其他经验',
  },
} as const;

type LabelMapName = keyof typeof labelMaps;

function toDisplayText(value?: string | number | null): string {
  if (value == null || value === '') {
    return '';
  }
  return String(value);
}

export function enumLabel(mapName: LabelMapName, value?: string | number | null, fallback = '待同步'): string {
  const text = toDisplayText(value);
  if (!text) {
    return fallback;
  }
  const map = labelMaps[mapName] as Record<string, string>;
  return map[text] ?? text;
}

export function positionLabel(value?: string | null): string {
  const text = toDisplayText(value);
  if (!text) {
    return '位置待定';
  }
  return enumLabel('position', text, '位置待定');
}

export function lineupRoleLabel(value?: string | null): string {
  const text = toDisplayText(value);
  if (!text) {
    return '角色待定';
  }
  return enumLabel('lineupRole', text, '角色待定');
}

export function matchStatusLabel(value?: string | null): string {
  return enumLabel('matchStatus', value, '状态待同步');
}

export function sourceTypeLabel(value?: string | null): string {
  return enumLabel('sourceType', value, '来源类型待定');
}

export function factTypeLabel(value?: string | null): string {
  return enumLabel('factType', value, '事实类型待定');
}

export function marketLabel(code?: string | null, name?: string | null): string {
  const codeLabel = enumLabel('marketCode', code, '');
  if (name && codeLabel && name !== code) {
    return `${codeLabel}（${name}）`;
  }
  return codeLabel || name || '玩法待定';
}

export function fieldNameLabel(value?: string | null): string {
  return enumLabel('fieldName', value, '字段待定');
}

export function readablePublicText(value?: string | null, fallback = '暂无公开摘要。'): string {
  const text = value?.trim();
  if (!text) {
    return fallback;
  }
  return text
    .replace(/ESPN状态=/gi, 'ESPN 状态：')
    .replace(/ESPN status=/gi, 'ESPN 状态：')
    .replace(/比分=/g, '比分：')
    .replace(/detail=/gi, '详情：')
    .replace(/None-None/gi, '待定')
    .replace(/\bSCHEDULED\b/g, '未开赛')
    .replace(/\bFINISHED\b/g, '已完赛')
    .replace(/\bFINAL\b/g, '已完赛')
    .replace(/\bUNKNOWN\b/g, '待确认')
    .replace(/;/g, '；');
}
